<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * New Settings-section reference entities, same idea as NamedLocation's
 * wifiSsid: known networks/BT devices worth recognizing on their own for
 * presence/context matching (see the LLM wiki's
 * features/current-state-tool.md) — not wired into that tool yet.
 */
final class Version20260829164607 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add named_network and named_bluetooth_device tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE named_bluetooth_device (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, device_name VARCHAR(255) DEFAULT NULL, mac_address VARCHAR(17) DEFAULT NULL, notes TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE named_network (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, ssid VARCHAR(255) NOT NULL, notes TEXT DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE named_bluetooth_device');
        $this->addSql('DROP TABLE named_network');
    }
}
